[project]
name = "frau-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "pandas>=2.3.3",
    "selenium>=4.38.0",
    "streamlit>=1.51.0",
    "webdriver-manager>=4.0.2",
]
